system:
    base_dir: ""
model:
    embedding_dimensions : 64
    hidden_dimensions : 64
    number_iterations : 7
train:
    num_epochs: 50
    lr: 0.01 #2e-5
    weight_decay: 1e-10
    gradient_clip_val: 0.65

data:
    num_workers: 4
    in_memory: True
    batch_size: 128
    test_ratio : 0.1
    box_size: 7  # Size of square box for pattern generation: B_n = {0,...,n-1}^2
    subbox_size: 5 # Size of subbox used to extract subpatterns
    alphabet: ['0','1','2'] # Alphabet of generated subshifts
    forbidden_propability: 0.3 # Probability for acceptance of pattern in the set of forbidden patterns.
    max_patterns: 10000 # Max number of patterns to generate for each SFT
    num_samples: 4 # Number of SFTs to generate
    folder_path : "patterns"
    samples_path : "samples.json"
    name: "subshift_2"

